### PR TITLE
feat: add geometry data type

### PR DESCRIPTION
**Pull request by ariesdevil**
Add new token `GEOMETRY` and new data type `Geometry`.

### CODE REVIEW

**Comment by everpcpc** [comment]
Bindings should also be updated for new type.

**Comment by ariesdevil** [comment]
> Bindings should also be updated for new type.↳

Done, PTAL again.

**Comment by everpcpc** [comment]
```
error[source-not-allowed]: detected 'git' source not explicitly allowed
    ┌─ /home/runner/work/bendsql/bendsql/Cargo.lock:107:16
    │
107 │ geozero 0.11.0 git+https://github.com/georust/geozero?rev=1d78b36
```

**Comment by ariesdevil** [comment]
> ```
> error[source-not-allowed]: detected 'git' source not explicitly allowed
>     ┌─ /home/runner/work/bendsql/bendsql/Cargo.lock:107:16
>     │
> 107 │ geozero 0.11.0 git+https://github.com/georust/geozero?rev=1d78b36
> ```

I don't know how to fix this...

**Comment by everpcpc** [comment]
git dependency is not allowed here.

**Comment by ariesdevil** [comment]
> https://github.com/georust/geozero

https://github.com/georust/geozero/pull/188#issuecomment-1920770994 I asked but no response...

**Comment by everpcpc** [comment]
Maybe we could fork and publish to a new crate?

**Comment by ariesdevil** [comment]
> Maybe we could fork and publish to a new crate?↳

This is a bit strange. GeoRust is an active development community, but I don't quite understand their release strategy.

**Comment by everpcpc** [comment]
geozero seems released 0.12.0

**Review by everpcpc — APPROVED** [review]

**Pull request merged**
